sudo: required
language: elixir
elixir:
  - 1.3.4
otp_release:
  - 19.1
services:
  - docker
before_install:
  - docker pull neo4j:3.0.6
  - docker run --publish=7484:7474 --env=NEO4J_AUTH=none -d neo4j
